### PR TITLE
fix t0, tf variable

### PR DESCRIPTION
**Pull request by ocots**

### CODE REVIEW

**Comment by ocots** [comment]
@jbcaillau Please review and merge.

**Review by jbcaillau — APPROVED** [review]
👍🏽 @ocots looks like the two points below from https://github.com/control-toolbox/CTFlows.jl/issues/15#issuecomment-2120829746 are addressed: 
> - the standard behaviour is (i) to forbid (= throw an exception) passing a variable to a `Fixed` problem, (ii) to force passing a variable to a `NonFixed = Variable` problem
> - two exceptions to (ii): for a dim $1$ variable equal either to `t0` or `tf`,  allow not to give `t0` or `tf` when calling a flow

**Comment by jbcaillau** [comment]
@ocots final thoughts: do we agree that calling a flow is the only case when default arguments (here `t0` and `tf`) may also be variable, hence creating a (functional but bizarre) duplication?

If yes, please merge 🤞🏾

**Comment by ocots** [comment]
> @ocots final thoughts: do we agree that calling a flow is the only case when default arguments (here `t0` and `tf`) may also be variable, hence creating a (functional but bizarre) duplication?
> 
> If yes, please merge 🤞🏾

I think yes. Note that when calling the flow, we could integrate until a time smaller than `tf`.

**Comment by jbcaillau** [comment]
> > @ocots final thoughts: do we agree that calling a flow is the only case when default arguments (here `t0` and `tf`) may also be variable, hence creating a (functional but bizarre) duplication?
> > If yes, please merge 🤞🏾
> 
> I think yes. Note that when calling the flow, we could integrate until a time smaller than `tf`.

@ocots Ouh, very good point 👍🏽. Do we agree that the current behaviour is that `f(t0, x0, p0, t1)` with the final time being the only variable (similar case for initial time or both times variable) sets the variable to `t1`?

On top of that, need to document this (-> new issue).

**Comment by ocots** [comment]
> > > @ocots final thoughts: do we agree that calling a flow is the only case when default arguments (here `t0` and `tf`) may also be variable, hence creating a (functional but bizarre) duplication?
> > > If yes, please merge 🤞🏾
> > 
> > I think yes. Note that when calling the flow, we could integrate until a time smaller than `tf`.
> 
> @ocots Ouh, very good point 👍🏽. Do we agree that the current behaviour is that `f(t0, x0, p0, t1)` with the final time being the only variable (similar case for initial time or both times variable) sets the variable to `t1`?
> 

We agree. Note that if there are both variables. It is intended that the variable is in order the initial time and then the final. Not the converse.

> On top of that, need to document this (-> new issue).

**Pull request merged**
